export interface BlogArticle {
  slug: string
  title: string
  description: string
  date: string
  readingTime: string
  category: string
  categoryColor: string
  emoji: string
}

export const blogArticles: BlogArticle[] = [
  {
    slug: 'beliebteste-babynamen-2026',
    title: 'Die beliebtesten Babynamen 2026 in Deutschland',
    description: 'Welche Vornamen liegen 2026 im Trend? Wir analysieren die aktuellen Top-Namen für Mädchen und Jungen – mit überraschenden Auf- und Absteigern.',
    date: '2026-06-10',
    readingTime: '8 Min.',
    category: 'Trends',
    categoryColor: 'hsl(262,60%,55%)',
    emoji: '📈',
  },
  {
    slug: 'seltene-vornamen-mit-schoener-bedeutung',
    title: 'Seltene Vornamen mit wunderschöner Bedeutung',
    description: 'Du suchst einen außergewöhnlichen Namen? Hier findest du 30 seltene Vornamen für Mädchen und Jungen – mit Herkunft und Bedeutung.',
    date: '2026-06-08',
    readingTime: '8 Min.',
    category: 'Inspiration',
    categoryColor: 'hsl(340,75%,55%)',
    emoji: '💎',
  },
  {
    slug: 'babynamen-international-funktionieren',
    title: 'Babynamen, die international funktionieren',
    description: 'Ein Name, der in Deutschland, Frankreich und den USA gleich gut klingt? Diese Vornamen meistern den internationalen Aussprache-Test.',
    date: '2026-06-05',
    readingTime: '7 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '🌍',
  },
  {
    slug: 'tipps-fuer-die-namenswahl',
    title: '10 Tipps für die perfekte Namenswahl',
    description: 'Von der Klangprobe bis zum Geschwister-Check: Mit diesen 10 bewährten Tipps findest du den richtigen Namen für dein Baby.',
    date: '2026-06-02',
    readingTime: '8 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '✅',
  },
  {
    slug: 'namensreue-vermeiden',
    title: 'Namensreue vermeiden: Warum Eltern ihren Namensentscheid bereuen',
    description: 'Studien zeigen: Bis zu 20% der Eltern bereuen die Namenswahl. Erfahre die häufigsten Gründe – und wie du es besser machst.',
    date: '2026-05-28',
    readingTime: '6 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '🤔',
  },
  {
    slug: 'was-dein-vorname-ueber-dich-verraet',
    title: 'Was dein Vorname über dich verrät – laut Wissenschaft',
    description: 'Beeinflusst der Name die Karriere? Studien zum „Dorian-Gray-Effekt", Vorurteilen bei Bewerbungen und dem Einfluss von Vornamen auf das Leben.',
    date: '2026-05-25',
    readingTime: '7 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '🔬',
  },
  {
    slug: 'alte-deutsche-vornamen-comeback',
    title: 'Alte deutsche Vornamen feiern ihr Comeback',
    description: 'Karl, Frieda, Theodor, Mathilde – klassische deutsche Namen sind zurück. Warum der Retro-Trend so stark ist und welche Namen jetzt angesagt sind.',
    date: '2026-05-20',
    readingTime: '7 Min.',
    category: 'Trends',
    categoryColor: 'hsl(262,60%,55%)',
    emoji: '🏰',
  },
  {
    slug: 'vorname-nachname-kombination',
    title: 'Vorname + Nachname: So findest du die perfekte Kombination',
    description: 'Reimgefahr, Silbenrhythmus, Initialen-Check: Warum die Kombination aus Vor- und Nachname genauso wichtig ist wie der Vorname selbst.',
    date: '2026-05-17',
    readingTime: '7 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '🔗',
  },
  {
    slug: 'babynamen-zwillinge',
    title: 'Zwillingsnamen: So findest du zwei Namen, die zusammenpassen',
    description: 'Zwillinge benennen ist doppelt so schwer. Harmonie ohne Verwechslungsgefahr, gleicher Stil, individuelle Identität – der ultimative Guide.',
    date: '2026-05-14',
    readingTime: '7 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '👶👶',
  },
  {
    slug: 'babynamen-bedeutung-herkunft',
    title: 'Von Germanisch bis Hebräisch: Was Babynamen wirklich bedeuten',
    description: 'Die Herkunft eines Namens verrät mehr, als du denkst. Ein Überblick über die wichtigsten Namens-Ursprünge – mit überraschenden Bedeutungen.',
    date: '2026-05-10',
    readingTime: '7 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '📜',
  },
  {
    slug: 'babynamen-geschwister-harmonie',
    title: 'Geschwisternamen: So klingen Bruder und Schwester harmonisch',
    description: 'Das zweite Kind ist unterwegs – aber welcher Name passt zum Erstgeborenen? Die 4 Säulen harmonischer Geschwisternamen.',
    date: '2026-05-07',
    readingTime: '6 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '👧👦',
  },
  {
    slug: 'babynamen-standesamt-recht',
    title: 'Was das Standesamt zu deinem Wunschnamen sagt',
    description: 'Nicht jeder Name wird akzeptiert. Die wichtigsten Regeln, kuriose Fälle und wie du im Zweifelsfall deinen Wunschnamen durchsetzen kannst.',
    date: '2026-05-03',
    readingTime: '7 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '⚖️',
  },
  {
    slug: 'babynamen-zweiter-vorname',
    title: 'Braucht mein Kind einen Zweitnamen? 5 gute Gründe dafür',
    description: 'Ein Zweitname bietet Flexibilität, Tradition und einen Plan B. Wann er Sinn macht und wie du den perfekten Zweitnamen findest.',
    date: '2026-04-28',
    readingTime: '7 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '➕',
  },
  {
    slug: 'babynamen-psychologie-klang',
    title: 'Die Psychologie des Namensklangs: Warum manche Namen besser klingen',
    description: 'Bouba-Kiki-Effekt, Vokalwirkung, Fluency-Effekt: Wie der Klang eines Namens unbewusst unser Bild von einer Person formt.',
    date: '2026-04-24',
    readingTime: '8 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '🧠',
  },
  {
    slug: 'babynamen-doppelnamen-guide',
    title: 'Doppelnamen mit Bindestrich: Wann sie Sinn machen (und wann nicht)',
    description: 'Marie-Sophie oder Marie Sophie? Der große Guide zu Doppelnamen – mit goldenen Regeln, häufigen Fehlern und den besten Kombinationen.',
    date: '2026-04-20',
    readingTime: '7 Min.',
    category: 'Ratgeber',
    categoryColor: 'hsl(170,60%,45%)',
    emoji: '➖',
  },
  {
    slug: 'babynamen-trends-deutschland-oesterreich-schweiz',
    title: 'DACH-Vergleich: So unterschiedlich wählen Deutschland, Österreich und die Schweiz',
    description: 'Gleiche Sprache, andere Namen? Überraschende Unterschiede und Gemeinsamkeiten bei der Namenswahl in Deutschland, Österreich und der Schweiz.',
    date: '2026-04-16',
    readingTime: '7 Min.',
    category: 'Trends',
    categoryColor: 'hsl(262,60%,55%)',
    emoji: '🇩🇪🇦🇹🇨🇭',
  },
  {
    slug: 'babynamen-aus-literatur-und-popkultur',
    title: 'Von Harry bis Hermine: Wie Bücher und Filme unsere Namenswahl beeinflussen',
    description: 'Astrid Lindgren, Harry Potter, Game of Thrones – wie die Popkultur Babynamen-Trends antreibt und welche Risiken das birgt.',
    date: '2026-04-12',
    readingTime: '8 Min.',
    category: 'Wissen',
    categoryColor: 'hsl(43,74%,50%)',
    emoji: '📚',
  },
]

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return blogArticles.find(a => a.slug === slug)
}