import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

interface NameSeed {
  name: string
  origin: string
  meaningDe: string
  meaningEn: string
  meaningEs: string
  gender: string
  region: string
  bullyingScore: number
  intlScore: number
  careerScore: number
  trendScore: number
  explanationDe: string
  explanationEn: string
  explanationEs: string
  popularity: number
  yearPeak: number | null
}

function calcRegret(b: number, i: number, c: number, t: number): number {
  return Math.round((b * 3 + i * 2.5 + c * 2.5 + t * 2) * 10 / 10)
}

const names: NameSeed[] = [
  // === GERMAN NAMES ===
  { name: 'Maximilian', origin: 'Lateinisch', meaningDe: 'Der Größte', meaningEn: 'The Greatest', meaningEs: 'El Más Grande', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 4, explanationDe: 'Klassischer deutscher Name mit hohem Ansehen. Kann zu Max abgekürzt werden.', explanationEn: 'Classic German name with high prestige. Can be shortened to Max.', explanationEs: 'Nombre clásico alemán con gran prestigio. Se puede acortar a Max.', popularity: 85, yearPeak: 2010 },
  { name: 'Sophie', origin: 'Griechisch', meaningDe: 'Die Weise', meaningEn: 'The Wise One', meaningEs: 'La Sabia', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'International verständlich und elegant. Sehr beliebter Klassiker.', explanationEn: 'Internationally understood and elegant. Very popular classic.', explanationEs: 'Internacionalmente comprensible y elegante. Clásico muy popular.', popularity: 90, yearPeak: 2005 },
  { name: 'Leon', origin: 'Griechisch', meaningDe: 'Der Löwe', meaningEn: 'The Lion', meaningEs: 'El León', gender: 'm', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Kurz, stark, international. Allerdings derzeit extrem populär – Verwechslungsgefahr.', explanationEn: 'Short, strong, international. However extremely popular right now – risk of confusion.', explanationEs: 'Corto, fuerte, internacional. Sin embargo, extremadamente popular ahora.', popularity: 95, yearPeak: 2020 },
  { name: 'Emma', origin: 'Germanisch', meaningDe: 'Die Allumfassende', meaningEn: 'The Universal One', meaningEs: 'La Universal', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 6, explanationDe: 'Wunderschöner Name, aber derzeit in vielen Ländern gleichzeitig auf Platz 1 – Trend-Risiko.', explanationEn: 'Beautiful name, but currently #1 in many countries simultaneously – trend risk.', explanationEs: 'Nombre hermoso, pero actualmente #1 en muchos países simultáneamente.', popularity: 98, yearPeak: 2018 },
  { name: 'Alexander', origin: 'Griechisch', meaningDe: 'Der Beschützer', meaningEn: 'The Protector', meaningEs: 'El Protector', gender: 'm', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Zeitloser Klassiker mit starker Bedeutung. Funktioniert in allen Kulturen.', explanationEn: 'Timeless classic with strong meaning. Works in all cultures.', explanationEs: 'Clásico atemporal con significado fuerte. Funciona en todas las culturas.', popularity: 80, yearPeak: 1995 },
  { name: 'Mia', origin: 'Skandinavisch', meaningDe: 'Die Geliebte', meaningEn: 'The Beloved', meaningEs: 'La Amada', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 6, explanationDe: 'Süß und kurz, aber extrem überbenutzt in den letzten 10 Jahren.', explanationEn: 'Sweet and short, but extremely overused in the last 10 years.', explanationEs: 'Dulce y corto, pero extremadamente usado en los últimos 10 años.', popularity: 95, yearPeak: 2015 },
  { name: 'Finn', origin: 'Irisch/Nordisch', meaningDe: 'Der Blonde/Helle', meaningEn: 'The Fair One', meaningEs: 'El Rubio/Claro', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Moderner Trendname. Klingt frisch, aber hohe Sättigungsgefahr.', explanationEn: 'Modern trend name. Sounds fresh, but high saturation risk.', explanationEs: 'Nombre moderno de tendencia. Suena fresco, pero riesgo de saturación.', popularity: 88, yearPeak: 2019 },
  { name: 'Hannah', origin: 'Hebräisch', meaningDe: 'Die Anmutige', meaningEn: 'The Graceful One', meaningEs: 'La Agraciada', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Palindrom-Name, international, zeitlos. Sehr sichere Wahl.', explanationEn: 'Palindrome name, international, timeless. Very safe choice.', explanationEs: 'Nombre palíndromo, internacional, atemporal. Elección muy segura.', popularity: 82, yearPeak: 2008 },
  { name: 'Lukas', origin: 'Griechisch', meaningDe: 'Der Lichtbringer', meaningEn: 'The Light Bearer', meaningEs: 'El Portador de Luz', gender: 'm', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'Solider Klassiker. In Deutschland seit Jahrzehnten beliebt.', explanationEn: 'Solid classic. Popular in Germany for decades.', explanationEs: 'Clásico sólido. Popular en Alemania durante décadas.', popularity: 80, yearPeak: 2005 },
  { name: 'Emilia', origin: 'Lateinisch', meaningDe: 'Die Eifrige', meaningEn: 'The Eager One', meaningEs: 'La Diligente', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 5, explanationDe: 'Elegant und feminin. Aktuell sehr im Trend, könnte schnell übersättigt wirken.', explanationEn: 'Elegant and feminine. Currently very trendy, might feel oversaturated soon.', explanationEs: 'Elegante y femenino. Actualmente muy de moda, podría saturarse pronto.', popularity: 92, yearPeak: 2022 },
  { name: 'Ben', origin: 'Hebräisch', meaningDe: 'Der Sohn', meaningEn: 'The Son', meaningEs: 'El Hijo', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 1, careerScore: 3, trendScore: 5, explanationDe: 'Sehr kurz – kann in formellen Kontexten weniger seriös wirken. Extrem populär.', explanationEn: 'Very short – may seem less serious in formal contexts. Extremely popular.', explanationEs: 'Muy corto – puede parecer menos serio en contextos formales. Extremadamente popular.', popularity: 90, yearPeak: 2018 },
  { name: 'Charlotte', origin: 'Französisch', meaningDe: 'Die Freie', meaningEn: 'The Free Woman', meaningEs: 'La Mujer Libre', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 3, explanationDe: 'Eleganter Name mit royalem Touch. Aussprache variiert stark je nach Sprache.', explanationEn: 'Elegant name with royal touch. Pronunciation varies greatly by language.', explanationEs: 'Nombre elegante con toque real. La pronunciación varía mucho según el idioma.', popularity: 75, yearPeak: 2015 },
  { name: 'Elias', origin: 'Hebräisch', meaningDe: 'Mein Gott ist Jahwe', meaningEn: 'My God is Yahweh', meaningEs: 'Mi Dios es Yahvé', gender: 'm', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 4, explanationDe: 'Biblischer Name, der modern klingt. Im Aufstieg, aber nicht übersättigt.', explanationEn: 'Biblical name that sounds modern. Rising, but not oversaturated.', explanationEs: 'Nombre bíblico que suena moderno. En ascenso, pero no saturado.', popularity: 85, yearPeak: 2021 },
  { name: 'Marie', origin: 'Hebräisch', meaningDe: 'Die Geliebte', meaningEn: 'The Beloved', meaningEs: 'La Amada', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Zeitloser Dauerbrenner. Funktioniert als Erst- und Zweitname perfekt.', explanationEn: 'Timeless evergreen. Works perfectly as first or middle name.', explanationEs: 'Clásico atemporal. Funciona perfectamente como primer o segundo nombre.', popularity: 85, yearPeak: 2000 },
  { name: 'Jonas', origin: 'Hebräisch', meaningDe: 'Die Taube', meaningEn: 'The Dove', meaningEs: 'La Paloma', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Beliebter nordischer Name. "Jonas Brothers" Assoziation kann nerven.', explanationEn: 'Popular Nordic name. "Jonas Brothers" association can be annoying.', explanationEs: 'Nombre nórdico popular. La asociación con "Jonas Brothers" puede molestar.', popularity: 78, yearPeak: 2012 },
  { name: 'Lina', origin: 'Arabisch/Germanisch', meaningDe: 'Die Zarte', meaningEn: 'The Tender One', meaningEs: 'La Tierna', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Weich und melodisch. Aktuell im Trend, multikulturell einsetzbar.', explanationEn: 'Soft and melodic. Currently trending, multicultural friendly.', explanationEs: 'Suave y melódico. Actualmente en tendencia, multicultural.', popularity: 82, yearPeak: 2020 },
  { name: 'Felix', origin: 'Lateinisch', meaningDe: 'Der Glückliche', meaningEn: 'The Happy One', meaningEs: 'El Feliz', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 2, careerScore: 2, trendScore: 2, explanationDe: 'Positive Bedeutung, aber "Felix die Katze" Assoziation bei Älteren.', explanationEn: 'Positive meaning, but "Felix the Cat" association with older generations.', explanationEs: 'Significado positivo, pero asociación con "Felix el Gato" en generaciones mayores.', popularity: 72, yearPeak: 2008 },
  { name: 'Johanna', origin: 'Hebräisch', meaningDe: 'Gott ist gnädig', meaningEn: 'God is Gracious', meaningEs: 'Dios es Misericordioso', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Traditionell und würdevoll. Aussprache im Englischen anders (Joanna).', explanationEn: 'Traditional and dignified. Pronunciation differs in English (Joanna).', explanationEs: 'Tradicional y digno. La pronunciación difiere en inglés (Joanna).', popularity: 65, yearPeak: 1998 },
  { name: 'Moritz', origin: 'Lateinisch', meaningDe: 'Der Dunkle', meaningEn: 'The Dark One', meaningEs: 'El Oscuro', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 5, careerScore: 2, trendScore: 3, explanationDe: 'Sehr deutsch. "Max und Moritz" Assoziation. International schwer aussprechbar.', explanationEn: 'Very German. "Max and Moritz" association. Hard to pronounce internationally.', explanationEs: 'Muy alemán. Asociación con "Max y Moritz". Difícil de pronunciar internacionalmente.', popularity: 55, yearPeak: 2005 },
  { name: 'Frieda', origin: 'Germanisch', meaningDe: 'Die Friedliche', meaningEn: 'The Peaceful One', meaningEs: 'La Pacífica', gender: 'f', region: 'de', bullyingScore: 3, intlScore: 4, careerScore: 3, trendScore: 4, explanationDe: 'Retro-Name im Comeback. Kann altmodisch wirken, aber gerade deshalb trendy.', explanationEn: 'Retro name making a comeback. Can seem old-fashioned, but trendy because of it.', explanationEs: 'Nombre retro en regreso. Puede parecer anticuado, pero es tendencia por eso.', popularity: 60, yearPeak: 2023 },
  { name: 'Paul', origin: 'Lateinisch', meaningDe: 'Der Kleine', meaningEn: 'The Small One', meaningEs: 'El Pequeño', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Kurz, klar, international. Bedeutung ("der Kleine") ist etwas unglücklich.', explanationEn: 'Short, clear, international. Meaning ("the small one") is slightly unfortunate.', explanationEs: 'Corto, claro, internacional. El significado ("el pequeño") es algo desafortunado.', popularity: 78, yearPeak: 2010 },
  { name: 'Mathilda', origin: 'Germanisch', meaningDe: 'Die Mächtige Kämpferin', meaningEn: 'The Mighty Warrior', meaningEs: 'La Poderosa Guerrera', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 4, explanationDe: 'Starker Retro-Name. Roald Dahl Assoziation positiv. Aussprache variiert.', explanationEn: 'Strong retro name. Roald Dahl association is positive. Pronunciation varies.', explanationEs: 'Nombre retro fuerte. Asociación con Roald Dahl positiva. La pronunciación varía.', popularity: 68, yearPeak: 2021 },
  { name: 'Noah', origin: 'Hebräisch', meaningDe: 'Der Ruhende', meaningEn: 'The Restful One', meaningEs: 'El Tranquilo', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 1, careerScore: 2, trendScore: 6, explanationDe: 'Weltweit #1 Trend-Name. Schön, aber in 10 Jahren wird jeder 3. Junge so heißen.', explanationEn: 'World\'s #1 trend name. Beautiful, but in 10 years every 3rd boy may have it.', explanationEs: 'Nombre tendencia #1 en el mundo. Hermoso, pero en 10 años será muy común.', popularity: 97, yearPeak: 2023 },
  { name: 'Ella', origin: 'Germanisch', meaningDe: 'Die Fremde', meaningEn: 'The Foreign One', meaningEs: 'La Extranjera', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Elegant und einfach. Aber sehr populär – häufig in Kitas.', explanationEn: 'Elegant and simple. But very popular – common in daycares.', explanationEs: 'Elegante y simple. Pero muy popular – común en guarderías.', popularity: 88, yearPeak: 2019 },
  { name: 'Friedrich', origin: 'Germanisch', meaningDe: 'Der Friedensreiche', meaningEn: 'The Peaceful Ruler', meaningEs: 'El Gobernante Pacífico', gender: 'm', region: 'de', bullyingScore: 4, intlScore: 6, careerScore: 1, trendScore: 3, explanationDe: 'Sehr traditionell, klingt nach Preußen. International kaum aussprechbar.', explanationEn: 'Very traditional, sounds Prussian. Nearly unpronounceable internationally.', explanationEs: 'Muy tradicional, suena prusiano. Casi impronunciable internacionalmente.', popularity: 35, yearPeak: 1920 },
  { name: 'Greta', origin: 'Griechisch', meaningDe: 'Die Perle', meaningEn: 'The Pearl', meaningEs: 'La Perla', gender: 'f', region: 'de', bullyingScore: 4, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Durch Greta Thunberg stark politisch aufgeladen. Kann polarisieren.', explanationEn: 'Strongly politically charged due to Greta Thunberg. Can be polarizing.', explanationEs: 'Fuertemente cargado políticamente por Greta Thunberg. Puede polarizar.', popularity: 65, yearPeak: 2019 },
  { name: 'Theodor', origin: 'Griechisch', meaningDe: 'Gottes Geschenk', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 3, careerScore: 1, trendScore: 4, explanationDe: 'Retro-Revival Name. Seriös, aber "Theo" als Spitzname lässig.', explanationEn: 'Retro-revival name. Serious, but "Theo" as nickname is casual.', explanationEs: 'Nombre de renacimiento retro. Serio, pero "Theo" como apodo es casual.', popularity: 62, yearPeak: 2022 },
  { name: 'Ida', origin: 'Germanisch', meaningDe: 'Die Arbeitende', meaningEn: 'The Industrious One', meaningEs: 'La Trabajadora', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Kurz und prägnant. Retro-Comeback, funktioniert international gut.', explanationEn: 'Short and concise. Retro comeback, works well internationally.', explanationEs: 'Corto y conciso. Retorno retro, funciona bien internacionalmente.', popularity: 58, yearPeak: 2021 },
  { name: 'Liam', origin: 'Irisch', meaningDe: 'Der entschlossene Beschützer', meaningEn: 'The Resolute Protector', meaningEs: 'El Protector Decidido', gender: 'm', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 7, explanationDe: '#1 in den USA seit Jahren. Wird bald auch in DE übersättigt sein.', explanationEn: '#1 in the US for years. Will soon be oversaturated in Germany too.', explanationEs: '#1 en EE.UU. por años. Pronto estará saturado también en Alemania.', popularity: 93, yearPeak: 2024 },
  { name: 'Clara', origin: 'Lateinisch', meaningDe: 'Die Helle/Berühmte', meaningEn: 'The Bright/Famous One', meaningEs: 'La Brillante/Famosa', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Elegant, klar, zeitlos. Eine der sichersten Namenswahlen.', explanationEn: 'Elegant, clear, timeless. One of the safest name choices.', explanationEs: 'Elegante, claro, atemporal. Una de las opciones más seguras.', popularity: 72, yearPeak: 2018 },
  { name: 'Henrik', origin: 'Germanisch', meaningDe: 'Der Hausherr', meaningEn: 'The Ruler of the Home', meaningEs: 'El Señor del Hogar', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Nordisch-elegant. Solide, aber nicht langweilig. Gute Balance.', explanationEn: 'Nordic-elegant. Solid, but not boring. Good balance.', explanationEs: 'Nórdico-elegante. Sólido, pero no aburrido. Buen equilibrio.', popularity: 45, yearPeak: 2010 },
  { name: 'Amelie', origin: 'Französisch', meaningDe: 'Die Tapfere', meaningEn: 'The Brave One', meaningEs: 'La Valiente', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 4, explanationDe: 'Französischer Charme, Film-Assoziation positiv. Beliebt in DE.', explanationEn: 'French charm, positive film association. Popular in Germany.', explanationEs: 'Encanto francés, asociación cinematográfica positiva. Popular en Alemania.', popularity: 70, yearPeak: 2012 },
  { name: 'Karl', origin: 'Germanisch', meaningDe: 'Der Freie Mann', meaningEn: 'The Free Man', meaningEs: 'El Hombre Libre', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 3, careerScore: 2, trendScore: 3, explanationDe: 'Karl Marx und Karl Lagerfeld – polarisierende Assoziationen. Retro-Charme.', explanationEn: 'Karl Marx and Karl Lagerfeld – polarizing associations. Retro charm.', explanationEs: 'Karl Marx y Karl Lagerfeld – asociaciones polarizantes. Encanto retro.', popularity: 42, yearPeak: 2020 },
  { name: 'Lotte', origin: 'Germanisch', meaningDe: 'Die Freie', meaningEn: 'The Free One', meaningEs: 'La Libre', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 4, explanationDe: 'Kurzform von Charlotte. Fröhlich und unkompliziert. Retro-Trend.', explanationEn: 'Short form of Charlotte. Cheerful and uncomplicated. Retro trend.', explanationEs: 'Forma corta de Charlotte. Alegre y sin complicaciones. Tendencia retro.', popularity: 50, yearPeak: 2022 },
  { name: 'Oskar', origin: 'Germanisch', meaningDe: 'Göttlicher Speer', meaningEn: 'Divine Spear', meaningEs: 'Lanza Divina', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 3, careerScore: 2, trendScore: 4, explanationDe: 'Retro-Revival. "Oscar" international besser, aber deutsche Schreibweise charmant.', explanationEn: 'Retro revival. "Oscar" works better internationally, but German spelling is charming.', explanationEs: 'Resurgimiento retro. "Oscar" funciona mejor internacionalmente.', popularity: 55, yearPeak: 2021 },
  { name: 'Mila', origin: 'Slawisch', meaningDe: 'Die Liebe/Anmutige', meaningEn: 'The Dear/Gracious One', meaningEs: 'La Querida/Graciosa', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 6, explanationDe: 'Durch Mila Kunis bekannt. Kurz, süß, aber Trend-Name mit Sättigungsrisiko.', explanationEn: 'Known through Mila Kunis. Short, sweet, but trend name with saturation risk.', explanationEs: 'Conocido por Mila Kunis. Corto, dulce, pero nombre de tendencia con riesgo de saturación.', popularity: 88, yearPeak: 2022 },
  { name: 'Anton', origin: 'Lateinisch', meaningDe: 'Der Unschätzbare', meaningEn: 'The Priceless One', meaningEs: 'El Invaluable', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 3, explanationDe: 'Solider deutscher Name mit Retro-Charme. "Toni" als Spitzname möglich.', explanationEn: 'Solid German name with retro charm. "Toni" as nickname possible.', explanationEs: 'Nombre alemán sólido con encanto retro. "Toni" como apodo posible.', popularity: 55, yearPeak: 2018 },
  { name: 'Nora', origin: 'Irisch/Arabisch', meaningDe: 'Das Licht', meaningEn: 'The Light', meaningEs: 'La Luz', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'International, elegant, kurz. Sehr gute Wahl mit minimalem Risiko.', explanationEn: 'International, elegant, short. Very good choice with minimal risk.', explanationEs: 'Internacional, elegante, corto. Muy buena elección con riesgo mínimo.', popularity: 75, yearPeak: 2020 },
  { name: 'Matteo', origin: 'Italienisch', meaningDe: 'Geschenk Gottes', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Italienischer Charme, im Trend. Kann in DE etwas exotisch wirken.', explanationEn: 'Italian charm, trending. Can seem somewhat exotic in Germany.', explanationEs: 'Encanto italiano, en tendencia. Puede parecer algo exótico en Alemania.', popularity: 78, yearPeak: 2023 },
  { name: 'Leni', origin: 'Griechisch', meaningDe: 'Die Leuchtende', meaningEn: 'The Shining One', meaningEs: 'La Brillante', gender: 'f', region: 'de', bullyingScore: 3, intlScore: 3, careerScore: 3, trendScore: 5, explanationDe: 'Durch Heidi Klums Tochter bekannt. Leni Riefenstahl-Assoziation bei Älteren problematisch.', explanationEn: 'Known through Heidi Klum\'s daughter. Leni Riefenstahl association problematic for older generations.', explanationEs: 'Conocido por la hija de Heidi Klum. Asociación con Leni Riefenstahl problemática.', popularity: 72, yearPeak: 2021 },
  { name: 'Milan', origin: 'Slawisch', meaningDe: 'Der Liebe/Angenehme', meaningEn: 'The Dear/Pleasant One', meaningEs: 'El Querido/Agradable', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Verwechslung mit der Stadt Mailand. Multikulturell, aber trendabhängig.', explanationEn: 'Confusion with the city Milan. Multicultural, but trend-dependent.', explanationEs: 'Confusión con la ciudad Milán. Multicultural, pero dependiente de tendencias.', popularity: 70, yearPeak: 2022 },
  { name: 'Alma', origin: 'Lateinisch/Hebräisch', meaningDe: 'Die Nährende/Jungfrau', meaningEn: 'The Nourishing One/Maiden', meaningEs: 'La Nutricia/Doncella', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 1, careerScore: 2, trendScore: 4, explanationDe: 'Retro-Comeback, multikulturell einsetzbar. Schöne Klangfarbe.', explanationEn: 'Retro comeback, multicultural. Beautiful tonality.', explanationEs: 'Retorno retro, multicultural. Hermosa tonalidad.', popularity: 55, yearPeak: 2023 },
  { name: 'Niklas', origin: 'Griechisch', meaningDe: 'Sieg des Volkes', meaningEn: 'Victory of the People', meaningEs: 'Victoria del Pueblo', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 3, explanationDe: 'Solide, nordisch, zeitlos. Weniger Häufig als Nikolas oder Nicolas.', explanationEn: 'Solid, Nordic, timeless. Less common than Nikolas or Nicolas.', explanationEs: 'Sólido, nórdico, atemporal. Menos común que Nikolas o Nicolas.', popularity: 50, yearPeak: 2005 },
  { name: 'Lina', origin: 'Arabisch', meaningDe: 'Die Zarte', meaningEn: 'The Delicate One', meaningEs: 'La Delicada', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Multikulturell, weich, beliebt. Trendname mit Sättigungsrisiko.', explanationEn: 'Multicultural, soft, popular. Trend name with saturation risk.', explanationEs: 'Multicultural, suave, popular. Nombre de tendencia con riesgo de saturación.', popularity: 82, yearPeak: 2020 },
  { name: 'Philipp', origin: 'Griechisch', meaningDe: 'Der Pferdefreund', meaningEn: 'The Horse Lover', meaningEs: 'El Amante de los Caballos', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Klassisch und seriös. Verschiedene Schreibweisen können verwirren.', explanationEn: 'Classic and serious. Different spellings can be confusing.', explanationEs: 'Clásico y serio. Diferentes ortografías pueden confundir.', popularity: 48, yearPeak: 2000 },
  { name: 'Ronja', origin: 'Schwedisch', meaningDe: 'Gottes Freude', meaningEn: 'God\'s Joy', meaningEs: 'Alegría de Dios', gender: 'f', region: 'de', bullyingScore: 2, intlScore: 4, careerScore: 3, trendScore: 3, explanationDe: 'Astrid Lindgren Assoziation schön. International schwer aussprechbar.', explanationEn: 'Beautiful Astrid Lindgren association. Hard to pronounce internationally.', explanationEs: 'Hermosa asociación con Astrid Lindgren. Difícil de pronunciar internacionalmente.', popularity: 40, yearPeak: 2015 },
  { name: 'Kevin', origin: 'Irisch', meaningDe: 'Der Schöne', meaningEn: 'The Handsome One', meaningEs: 'El Hermoso', gender: 'm', region: 'de', bullyingScore: 8, intlScore: 1, careerScore: 7, trendScore: 7, explanationDe: '"Kevinismus" – in DE stark stigmatisiert. Studien zeigen Vorurteile bei Lehrern und Arbeitgebern.', explanationEn: '"Kevinism" – heavily stigmatized in Germany. Studies show bias from teachers and employers.', explanationEs: '"Kevinismo" – fuertemente estigmatizado en Alemania. Estudios muestran prejuicios de profesores y empleadores.', popularity: 30, yearPeak: 1995 },
  { name: 'Chantal', origin: 'Französisch', meaningDe: 'Die Singende', meaningEn: 'The Singer', meaningEs: 'La Cantante', gender: 'f', region: 'de', bullyingScore: 8, intlScore: 3, careerScore: 7, trendScore: 8, explanationDe: 'Ähnlich wie Kevin stark vorurteilsbelastet in DE. "Unterschicht"-Klischee.', explanationEn: 'Like Kevin, heavily prejudiced in Germany. "Lower class" cliché.', explanationEs: 'Como Kevin, muy prejuiciado en Alemania. Cliché de "clase baja".', popularity: 15, yearPeak: 1998 },
  { name: 'Jacqueline', origin: 'Französisch', meaningDe: 'Die Nachfolgerin', meaningEn: 'The Successor', meaningEs: 'La Sucesora', gender: 'f', region: 'de', bullyingScore: 7, intlScore: 4, careerScore: 6, trendScore: 8, explanationDe: 'In DE durch "Kevinismus" belastet. Oft falsch geschrieben und ausgesprochen.', explanationEn: 'Burdened by "Kevinism" in Germany. Often misspelled and mispronounced.', explanationEs: 'Cargado por "Kevinismo" en Alemania. A menudo mal escrito y pronunciado.', popularity: 12, yearPeak: 1996 },
  { name: 'Justin', origin: 'Lateinisch', meaningDe: 'Der Gerechte', meaningEn: 'The Just One', meaningEs: 'El Justo', gender: 'm', region: 'de', bullyingScore: 7, intlScore: 1, careerScore: 6, trendScore: 7, explanationDe: 'Ebenfalls "Kevinismus"-belastet in DE. Justin Bieber Assoziation.', explanationEn: 'Also burdened by "Kevinism" in Germany. Justin Bieber association.', explanationEs: 'También cargado por "Kevinismo" en Alemania. Asociación con Justin Bieber.', popularity: 25, yearPeak: 1998 },
  // === ENGLISH NAMES ===
  { name: 'James', origin: 'English/Hebrew', meaningDe: 'Der Nachfolger', meaningEn: 'The Supplanter', meaningEs: 'El Suplantador', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 1, explanationDe: 'Einer der zeitlosesten englischen Namen. Royal und professionell.', explanationEn: 'One of the most timeless English names. Royal and professional.', explanationEs: 'Uno de los nombres ingleses más atemporales. Real y profesional.', popularity: 85, yearPeak: 1990 },
  { name: 'Olivia', origin: 'Latin', meaningDe: 'Der Olivenbaum', meaningEn: 'The Olive Tree', meaningEs: 'El Olivo', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 5, explanationDe: 'Weltweit beliebt und elegant. Aber extremer Trendname.', explanationEn: 'Globally popular and elegant. But extreme trend name.', explanationEs: 'Globalmente popular y elegante. Pero nombre de tendencia extremo.', popularity: 96, yearPeak: 2022 },
  { name: 'William', origin: 'Germanic', meaningDe: 'Der entschlossene Beschützer', meaningEn: 'The Resolute Protector', meaningEs: 'El Protector Decidido', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Königlicher Klassiker. Will, Willy, Bill als Kurzformen. Zeitlos.', explanationEn: 'Royal classic. Will, Willy, Bill as short forms. Timeless.', explanationEs: 'Clásico real. Will, Willy, Bill como formas cortas. Atemporal.', popularity: 80, yearPeak: 2010 },
  { name: 'Ava', origin: 'Latin/Germanic', meaningDe: 'Die Lebendige', meaningEn: 'The Living One', meaningEs: 'La Viviente', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 5, explanationDe: 'Kurz und elegant. Hollywood-Glamour (Ava Gardner). Sehr trendy.', explanationEn: 'Short and elegant. Hollywood glamour (Ava Gardner). Very trendy.', explanationEs: 'Corto y elegante. Glamour de Hollywood (Ava Gardner). Muy de moda.', popularity: 90, yearPeak: 2020 },
  { name: 'Oliver', origin: 'Latin', meaningDe: 'Der Olivenbaum-Pflanzer', meaningEn: 'The Olive Tree Planter', meaningEs: 'El Plantador de Olivos', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Charmant und international. Oliver Twist Assoziation.', explanationEn: 'Charming and international. Oliver Twist association.', explanationEs: 'Encantador e internacional. Asociación con Oliver Twist.', popularity: 88, yearPeak: 2021 },
  { name: 'Isabella', origin: 'Spanish/Italian', meaningDe: 'Die Gott Geweihte', meaningEn: 'Devoted to God', meaningEs: 'Devota a Dios', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Elegant mit vielen Kurzformen (Bella, Izzy). Twilight-Assoziation.', explanationEn: 'Elegant with many nicknames (Bella, Izzy). Twilight association.', explanationEs: 'Elegante con muchos apodos (Bella, Izzy). Asociación con Twilight.', popularity: 82, yearPeak: 2012 },
  { name: 'Henry', origin: 'Germanic', meaningDe: 'Der Herrscher des Heims', meaningEn: 'Ruler of the Home', meaningEs: 'Gobernante del Hogar', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'Königlich, klassisch, charmant. Harry als Kurzform beliebt.', explanationEn: 'Royal, classic, charming. Harry as a popular short form.', explanationEs: 'Real, clásico, encantador. Harry como forma corta popular.', popularity: 78, yearPeak: 2018 },
  { name: 'Amelia', origin: 'Germanic', meaningDe: 'Die Tapfere', meaningEn: 'The Industrious One', meaningEs: 'La Trabajadora', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 5, explanationDe: 'Amelia Earhart Assoziation inspirierend. Sehr beliebt aktuell.', explanationEn: 'Amelia Earhart association inspiring. Very popular currently.', explanationEs: 'Asociación con Amelia Earhart inspiradora. Muy popular actualmente.', popularity: 92, yearPeak: 2023 },
  { name: 'Theodore', origin: 'Greek', meaningDe: 'Gottes Geschenk', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 4, explanationDe: 'Retro-Chic mit dem Spitznamen Theo. Teddy Roosevelt Assoziation.', explanationEn: 'Retro-chic with nickname Theo. Teddy Roosevelt association.', explanationEs: 'Retro-chic con apodo Theo. Asociación con Teddy Roosevelt.', popularity: 75, yearPeak: 2023 },
  { name: 'Harper', origin: 'English', meaningDe: 'Harfenspieler', meaningEn: 'Harp Player', meaningEs: 'Tocador de Arpa', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 5, explanationDe: 'Unisex-Trendname. International schwer aussprechbar. David Beckhams Tochter.', explanationEn: 'Unisex trend name. Hard to pronounce internationally. David Beckham\'s daughter.', explanationEs: 'Nombre de tendencia unisex. Difícil de pronunciar internacionalmente. Hija de David Beckham.', popularity: 78, yearPeak: 2015 },
  { name: 'Jack', origin: 'English', meaningDe: 'Gott ist gnädig', meaningEn: 'God is Gracious', meaningEs: 'Dios es Misericordioso', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'Klassischer "Jedermann"-Name. Einfach, männlich, vielseitig.', explanationEn: 'Classic "everyman" name. Simple, masculine, versatile.', explanationEs: 'Nombre clásico de "hombre común". Simple, masculino, versátil.', popularity: 80, yearPeak: 2008 },
  { name: 'Sophia', origin: 'Greek', meaningDe: 'Die Weise', meaningEn: 'The Wise One', meaningEs: 'La Sabia', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Weltweit in den Top 10. Elegant und intelligent klingend.', explanationEn: 'Worldwide top 10. Elegant and intelligent sounding.', explanationEs: 'Top 10 mundial. Suena elegante e inteligente.', popularity: 92, yearPeak: 2015 },
  { name: 'Ethan', origin: 'Hebrew', meaningDe: 'Der Starke', meaningEn: 'The Strong One', meaningEs: 'El Fuerte', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Modern und stark klingend. In den USA sehr verbreitet.', explanationEn: 'Modern and strong sounding. Very common in the US.', explanationEs: 'Moderno y de sonido fuerte. Muy común en EE.UU.', popularity: 82, yearPeak: 2010 },
  { name: 'Scarlett', origin: 'English', meaningDe: 'Die Scharlachrote', meaningEn: 'The Red One', meaningEs: 'La Escarlata', gender: 'f', region: 'en', bullyingScore: 3, intlScore: 3, careerScore: 2, trendScore: 5, explanationDe: 'Vom Winde verweht und Scarlett Johansson. Auffällig, aber trendy.', explanationEn: 'Gone with the Wind and Scarlett Johansson. Striking but trendy.', explanationEs: 'Lo que el Viento se Llevó y Scarlett Johansson. Llamativo pero de moda.', popularity: 75, yearPeak: 2020 },
  { name: 'Sebastian', origin: 'Greek', meaningDe: 'Der Erhabene', meaningEn: 'The Revered One', meaningEs: 'El Venerable', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Zeitlos, seriös, international. Etwas länger, aber mit Spitznamen "Basti/Seb".', explanationEn: 'Timeless, serious, international. A bit long, but with nicknames "Seb/Bash".', explanationEs: 'Atemporal, serio, internacional. Un poco largo, pero con apodos "Seb".', popularity: 65, yearPeak: 2005 },
  { name: 'Aria', origin: 'Italian/Hebrew', meaningDe: 'Die Melodie', meaningEn: 'The Melody', meaningEs: 'La Melodía', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 6, explanationDe: 'Game of Thrones Effekt. Wunderschön, aber extrem im Trend.', explanationEn: 'Game of Thrones effect. Beautiful, but extremely trendy.', explanationEs: 'Efecto Game of Thrones. Hermoso, pero extremadamente de moda.', popularity: 85, yearPeak: 2022 },
  { name: 'Benjamin', origin: 'Hebrew', meaningDe: 'Sohn der rechten Hand', meaningEn: 'Son of the Right Hand', meaningEs: 'Hijo de la Mano Derecha', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Zeitloser Klassiker. Ben als Kurzform modern. Sehr sichere Wahl.', explanationEn: 'Timeless classic. Ben as short form is modern. Very safe choice.', explanationEs: 'Clásico atemporal. Ben como forma corta es moderno. Elección muy segura.', popularity: 75, yearPeak: 2000 },
  { name: 'Luna', origin: 'Latin', meaningDe: 'Der Mond', meaningEn: 'The Moon', meaningEs: 'La Luna', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 1, careerScore: 2, trendScore: 7, explanationDe: 'Harry Potter und Chrissy Teigen. Extremer Trendname, wird bald übersättigt.', explanationEn: 'Harry Potter and Chrissy Teigen. Extreme trend name, will be oversaturated soon.', explanationEs: 'Harry Potter y Chrissy Teigen. Nombre de tendencia extremo, se saturará pronto.', popularity: 90, yearPeak: 2023 },
  { name: 'Samuel', origin: 'Hebrew', meaningDe: 'Von Gott erhört', meaningEn: 'Heard by God', meaningEs: 'Escuchado por Dios', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Biblischer Klassiker. Sam als Spitzname sympathisch. Zeitlos.', explanationEn: 'Biblical classic. Sam as nickname is likeable. Timeless.', explanationEs: 'Clásico bíblico. Sam como apodo es simpático. Atemporal.', popularity: 72, yearPeak: 2008 },
  { name: 'Grace', origin: 'English', meaningDe: 'Die Anmutige', meaningEn: 'Grace/Elegance', meaningEs: 'La Gracia/Elegancia', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Tugendname, elegant und zeitlos. Grace Kelly Assoziation.', explanationEn: 'Virtue name, elegant and timeless. Grace Kelly association.', explanationEs: 'Nombre de virtud, elegante y atemporal. Asociación con Grace Kelly.', popularity: 70, yearPeak: 2005 },
  { name: 'Daniel', origin: 'Hebrew', meaningDe: 'Gott ist mein Richter', meaningEn: 'God is My Judge', meaningEs: 'Dios es Mi Juez', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Einer der internationalsten Namen überhaupt. Funktioniert überall.', explanationEn: 'One of the most international names ever. Works everywhere.', explanationEs: 'Uno de los nombres más internacionales. Funciona en todas partes.', popularity: 78, yearPeak: 2000 },
  { name: 'Chloe', origin: 'Greek', meaningDe: 'Der junge Trieb', meaningEn: 'The Young Shoot', meaningEs: 'El Brote Joven', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 4, explanationDe: 'Griechischer Charme, aber Aussprache variiert stark (Klo-i vs. Schlo-e).', explanationEn: 'Greek charm, but pronunciation varies greatly across languages.', explanationEs: 'Encanto griego, pero la pronunciación varía mucho entre idiomas.', popularity: 72, yearPeak: 2010 },
  { name: 'Matthew', origin: 'Hebrew', meaningDe: 'Geschenk Gottes', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Solider Klassiker. Englische "th"-Laute schwer für Nicht-Muttersprachler.', explanationEn: 'Solid classic. English "th" sounds difficult for non-native speakers.', explanationEs: 'Clásico sólido. Sonidos ingleses "th" difíciles para no nativos.', popularity: 72, yearPeak: 1998 },
  { name: 'Penelope', origin: 'Greek', meaningDe: 'Die Weberin', meaningEn: 'The Weaver', meaningEs: 'La Tejedora', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 4, explanationDe: 'Mythologisch und elegant. Penny als süßer Spitzname. Im Aufstieg.', explanationEn: 'Mythological and elegant. Penny as cute nickname. Rising.', explanationEs: 'Mitológico y elegante. Penny como apodo lindo. En ascenso.', popularity: 68, yearPeak: 2022 },
  { name: 'Thomas', origin: 'Aramaic', meaningDe: 'Der Zwilling', meaningEn: 'The Twin', meaningEs: 'El Gemelo', gender: 'm', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Ultra-klassisch, vielleicht etwas langweilig für manche. Tom als Kurzform.', explanationEn: 'Ultra-classic, perhaps a bit boring for some. Tom as short form.', explanationEs: 'Ultraclásico, quizás un poco aburrido para algunos. Tom como forma corta.', popularity: 65, yearPeak: 1990 },
  { name: 'Violet', origin: 'English/Latin', meaningDe: 'Das Veilchen', meaningEn: 'The Violet Flower', meaningEs: 'La Violeta', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 4, explanationDe: 'Romantisch und blumig. Im Trend durch Prominente.', explanationEn: 'Romantic and floral. Trending through celebrities.', explanationEs: 'Romántico y floral. En tendencia por celebridades.', popularity: 65, yearPeak: 2021 },
  { name: 'George', origin: 'Greek', meaningDe: 'Der Landarbeiter', meaningEn: 'The Farmer', meaningEs: 'El Agricultor', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'Königlicher Name (Prinz George). Solide und respektabel.', explanationEn: 'Royal name (Prince George). Solid and respectable.', explanationEs: 'Nombre real (Príncipe George). Sólido y respetable.', popularity: 68, yearPeak: 2015 },
  { name: 'Ruby', origin: 'English/Latin', meaningDe: 'Der Rubin', meaningEn: 'The Ruby Gem', meaningEs: 'El Rubí', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Edelstein-Name, lebendig und energisch. Auch Programmiersprachen-Assoziation.', explanationEn: 'Gemstone name, lively and energetic. Also programming language association.', explanationEs: 'Nombre de piedra preciosa, vivaz y enérgico. También asociación con lenguaje de programación.', popularity: 62, yearPeak: 2018 },
  { name: 'Arthur', origin: 'Celtic', meaningDe: 'Der Bär', meaningEn: 'The Bear', meaningEs: 'El Oso', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'König Artus Assoziation. Retro-Comeback in vielen Ländern.', explanationEn: 'King Arthur association. Retro comeback in many countries.', explanationEs: 'Asociación con el Rey Arturo. Retorno retro en muchos países.', popularity: 65, yearPeak: 2022 },
  { name: 'Ivy', origin: 'English', meaningDe: 'Der Efeu', meaningEn: 'The Ivy Plant', meaningEs: 'La Hiedra', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Natur-Name im Trend. Beyoncés Tochter Blue Ivy steigerte Beliebtheit.', explanationEn: 'Nature name trending. Beyoncé\'s daughter Blue Ivy boosted popularity.', explanationEs: 'Nombre de naturaleza en tendencia. La hija de Beyoncé, Blue Ivy, aumentó la popularidad.', popularity: 70, yearPeak: 2022 },
  { name: 'Edward', origin: 'English', meaningDe: 'Der reiche Hüter', meaningEn: 'The Rich Guardian', meaningEs: 'El Guardián Rico', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Königlich und traditionell. Ed, Eddie als Spitznamen. Twilight-Assoziation.', explanationEn: 'Royal and traditional. Ed, Eddie as nicknames. Twilight association.', explanationEs: 'Real y tradicional. Ed, Eddie como apodos. Asociación con Twilight.', popularity: 55, yearPeak: 2010 },
  { name: 'Willow', origin: 'English', meaningDe: 'Die Weide', meaningEn: 'The Willow Tree', meaningEs: 'El Sauce', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 3, careerScore: 3, trendScore: 5, explanationDe: 'Natur-Name, sanft und poetisch. Will Smith und Pink gaben ihren Töchtern diesen Namen.', explanationEn: 'Nature name, gentle and poetic. Will Smith and Pink named their daughters this.', explanationEs: 'Nombre de naturaleza, suave y poético. Will Smith y Pink nombraron así a sus hijas.', popularity: 60, yearPeak: 2021 },
  { name: 'Oscar', origin: 'Gaelic/English', meaningDe: 'Der Göttliche Speer', meaningEn: 'Divine Spear', meaningEs: 'Lanza Divina', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Film-Award Assoziation. International gut erkennbar und aussprechbar.', explanationEn: 'Film award association. Internationally well recognized and pronounceable.', explanationEs: 'Asociación con premio cinematográfico. Bien reconocido y pronunciable internacionalmente.', popularity: 70, yearPeak: 2020 },
  { name: 'Isla', origin: 'Scottish', meaningDe: 'Die Insel', meaningEn: 'The Island', meaningEs: 'La Isla', gender: 'f', region: 'en', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 5, explanationDe: 'Schön, aber das stille "s" verwirrt oft. Isla Fisher Assoziation.', explanationEn: 'Beautiful, but the silent "s" often confuses. Isla Fisher association.', explanationEs: 'Hermoso, pero la "s" silenciosa confunde. Asociación con Isla Fisher.', popularity: 78, yearPeak: 2022 },
  // === SPANISH NAMES ===
  { name: 'Mateo', origin: 'Hebreo', meaningDe: 'Geschenk Gottes', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: '#1 in Spanien. Warm und südländisch, aber sehr überstrapaziert.', explanationEn: '#1 in Spain. Warm and southern, but very overused.', explanationEs: '#1 en España. Cálido y sureño, pero muy sobreusado.', popularity: 95, yearPeak: 2022 },
  { name: 'Lucía', origin: 'Latino', meaningDe: 'Die Leuchtende', meaningEn: 'The Shining One', meaningEs: 'La que lleva la luz', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 4, explanationDe: 'Spanischer Dauerbrenner. Schön, klassisch, feminin.', explanationEn: 'Spanish evergreen. Beautiful, classic, feminine.', explanationEs: 'Clásico español perenne. Hermoso, clásico, femenino.', popularity: 92, yearPeak: 2018 },
  { name: 'Santiago', origin: 'Hebreo/Español', meaningDe: 'Der Heilige Jakob', meaningEn: 'Saint James', meaningEs: 'Santo Jacobo', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 4, explanationDe: 'Majestätisch und kulturell reich. Etwas lang, aber "Santi" als Kürzel.', explanationEn: 'Majestic and culturally rich. A bit long, but "Santi" as short form.', explanationEs: 'Majestuoso y culturalmente rico. Un poco largo, pero "Santi" como diminutivo.', popularity: 85, yearPeak: 2021 },
  { name: 'Valentina', origin: 'Latino', meaningDe: 'Die Starke/Gesunde', meaningEn: 'The Strong/Healthy One', meaningEs: 'La Fuerte/Saludable', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Romanisch und kraftvoll. International gut erkennbar.', explanationEn: 'Romance and powerful. Internationally well recognized.', explanationEs: 'Romance y poderoso. Bien reconocido internacionalmente.', popularity: 88, yearPeak: 2020 },
  { name: 'Diego', origin: 'Griego/Español', meaningDe: 'Der Lehrende', meaningEn: 'The Teacher', meaningEs: 'El que enseña', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'Diego Maradona/Rivera Assoziation. Stark und männlich.', explanationEn: 'Diego Maradona/Rivera association. Strong and masculine.', explanationEs: 'Asociación con Diego Maradona/Rivera. Fuerte y masculino.', popularity: 78, yearPeak: 2015 },
  { name: 'Camila', origin: 'Latino', meaningDe: 'Die Priesterin', meaningEn: 'The Priestess', meaningEs: 'La Sacerdotisa', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 5, explanationDe: 'Durch Camila Cabello international bekannt. Melodisch und elegant.', explanationEn: 'Known internationally through Camila Cabello. Melodic and elegant.', explanationEs: 'Conocido internacionalmente por Camila Cabello. Melódico y elegante.', popularity: 85, yearPeak: 2021 },
  { name: 'Alejandro', origin: 'Griego', meaningDe: 'Der Beschützer der Menschen', meaningEn: 'The Protector of Men', meaningEs: 'El Protector de los Hombres', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Spanische Form von Alexander. Elegant, aber international schwerer.', explanationEn: 'Spanish form of Alexander. Elegant, but harder internationally.', explanationEs: 'Forma española de Alejandro. Elegante y distinguido.', popularity: 75, yearPeak: 2010 },
  { name: 'Sofía', origin: 'Griego', meaningDe: 'Die Weise', meaningEn: 'The Wise One', meaningEs: 'La Sabia', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Spanische Sophia. Universell schön und gebildet klingend.', explanationEn: 'Spanish Sophia. Universally beautiful and educated sounding.', explanationEs: 'Universalmente hermoso y suena educado.', popularity: 90, yearPeak: 2018 },
  { name: 'Pablo', origin: 'Latino', meaningDe: 'Der Kleine', meaningEn: 'The Small One', meaningEs: 'El Pequeño', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 2, explanationDe: 'Pablo Picasso und Pablo Neruda. Stark kulturell aufgeladen.', explanationEn: 'Pablo Picasso and Pablo Neruda. Strongly culturally charged.', explanationEs: 'Pablo Picasso y Pablo Neruda. Fuertemente cargado culturalmente.', popularity: 72, yearPeak: 2012 },
  { name: 'Isabella', origin: 'Hebreo/Italiano', meaningDe: 'Die Gott Geweihte', meaningEn: 'Devoted to God', meaningEs: 'Devota a Dios', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Königlich spanisch. Isabella von Kastilien. Viele Kurzformen.', explanationEn: 'Royal Spanish. Isabella of Castile. Many short forms.', explanationEs: 'Realeza española. Isabel de Castilla. Muchas formas cortas.', popularity: 82, yearPeak: 2015 },
  { name: 'Hugo', origin: 'Germánico', meaningDe: 'Der Denkende', meaningEn: 'The Thinker', meaningEs: 'El Pensador', gender: 'm', region: 'es', bullyingScore: 3, intlScore: 1, careerScore: 2, trendScore: 4, explanationDe: 'Hugo Boss Assoziation. Kurz und markant. Im Trend in Spanien.', explanationEn: 'Hugo Boss association. Short and distinctive. Trending in Spain.', explanationEs: 'Asociación con Hugo Boss. Corto y distintivo. En tendencia en España.', popularity: 80, yearPeak: 2022 },
  { name: 'Martina', origin: 'Latino', meaningDe: 'Die dem Mars Geweihte', meaningEn: 'Devoted to Mars', meaningEs: 'Devota a Marte', gender: 'f', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'Martina Navratilova Assoziation. Stark und sportlich.', explanationEn: 'Martina Navratilova association. Strong and athletic.', explanationEs: 'Asociación con Martina Navratilova. Fuerte y atlético.', popularity: 65, yearPeak: 2018 },
  { name: 'Carlos', origin: 'Germánico', meaningDe: 'Der Freie Mann', meaningEn: 'The Free Man', meaningEs: 'El Hombre Libre', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Königlicher spanischer Klassiker. Karl auf Spanisch. Zeitlos.', explanationEn: 'Royal Spanish classic. Charles in Spanish. Timeless.', explanationEs: 'Clásico real español. Atemporal y distinguido.', popularity: 75, yearPeak: 2005 },
  { name: 'Elena', origin: 'Griego', meaningDe: 'Die Strahlende', meaningEn: 'The Radiant One', meaningEs: 'La Radiante', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Elegant und international. Funktioniert in praktisch allen Sprachen.', explanationEn: 'Elegant and international. Works in virtually all languages.', explanationEs: 'Elegante e internacional. Funciona en prácticamente todos los idiomas.', popularity: 80, yearPeak: 2016 },
  { name: 'Javier', origin: 'Basco', meaningDe: 'Das neue Haus', meaningEn: 'The New House', meaningEs: 'La Casa Nueva', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 2, explanationDe: 'Typisch spanisch. Die J-Aussprache variiert stark international.', explanationEn: 'Typically Spanish. The J pronunciation varies greatly internationally.', explanationEs: 'Típicamente español. La pronunciación de la J varía internacionalmente.', popularity: 65, yearPeak: 2000 },
  { name: 'Carmen', origin: 'Hebreo/Latino', meaningDe: 'Der Garten', meaningEn: 'The Garden', meaningEs: 'El Jardín', gender: 'f', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Oper von Bizet Assoziation. Traditionell, aber zeitlos elegant.', explanationEn: 'Bizet opera association. Traditional, but timelessly elegant.', explanationEs: 'Asociación con la ópera de Bizet. Tradicional, pero atemporalmente elegante.', popularity: 60, yearPeak: 1995 },
  { name: 'Marcos', origin: 'Latino', meaningDe: 'Dem Mars geweiht', meaningEn: 'Devoted to Mars', meaningEs: 'Devoto a Marte', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'Römische Herkunft. Solide und männlich klingend.', explanationEn: 'Roman origin. Solid and masculine sounding.', explanationEs: 'Origen romano. Suena sólido y masculino.', popularity: 68, yearPeak: 2012 },
  { name: 'Daniela', origin: 'Hebreo', meaningDe: 'Gott ist mein Richter', meaningEn: 'God is My Judge', meaningEs: 'Dios es Mi Juez', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Weibliche Form von Daniel. International und elegant.', explanationEn: 'Feminine form of Daniel. International and elegant.', explanationEs: 'Forma femenina de Daniel. Internacional y elegante.', popularity: 72, yearPeak: 2010 },
  { name: 'Álvaro', origin: 'Germánico', meaningDe: 'Der Wächter', meaningEn: 'The Guardian', meaningEs: 'El Guardián', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 3, explanationDe: 'Sehr spanisch mit Akzent. International schwerer zu schreiben.', explanationEn: 'Very Spanish with accent. Harder to write internationally.', explanationEs: 'Muy español con acento. Difícil de escribir internacionalmente.', popularity: 70, yearPeak: 2015 },
  { name: 'Paula', origin: 'Latino', meaningDe: 'Die Kleine', meaningEn: 'The Small One', meaningEs: 'La Pequeña', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'International, einfach, elegant. Weibliche Form von Paul.', explanationEn: 'International, simple, elegant. Feminine form of Paul.', explanationEs: 'Internacional, simple, elegante. Forma femenina de Pablo.', popularity: 78, yearPeak: 2018 },
  { name: 'Rodrigo', origin: 'Germánico', meaningDe: 'Der Ruhmreiche', meaningEn: 'The Glorious One', meaningEs: 'El Glorioso', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 3, explanationDe: 'El Cid Assoziation. Durch Olivia Rodrigo auch modern.', explanationEn: 'El Cid association. Also modern through Olivia Rodrigo.', explanationEs: 'Asociación con El Cid. También moderno por Olivia Rodrigo.', popularity: 60, yearPeak: 2021 },
  { name: 'María', origin: 'Hebreo', meaningDe: 'Die Geliebte', meaningEn: 'The Beloved', meaningEs: 'La Amada', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 1, explanationDe: 'DER klassische spanische Name schlechthin. Zeitlos, aber sehr häufig.', explanationEn: 'THE classic Spanish name par excellence. Timeless, but very common.', explanationEs: 'EL nombre clásico español por excelencia. Atemporal, pero muy común.', popularity: 85, yearPeak: 1980 },
  { name: 'Adriana', origin: 'Latino', meaningDe: 'Die aus Adria Stammende', meaningEn: 'From the Adriatic', meaningEs: 'La de Adria', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Elegant und exotisch. Adriana Lima als Namensboost.', explanationEn: 'Elegant and exotic. Adriana Lima as name boost.', explanationEs: 'Elegante y exótico. Adriana Lima como impulso del nombre.', popularity: 68, yearPeak: 2012 },
  { name: 'Rafael', origin: 'Hebreo', meaningDe: 'Gott hat geheilt', meaningEn: 'God has Healed', meaningEs: 'Dios ha Sanado', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Rafael Nadal Assoziation. Klassisch, stark, respektiert.', explanationEn: 'Rafael Nadal association. Classic, strong, respected.', explanationEs: 'Asociación con Rafael Nadal. Clásico, fuerte, respetado.', popularity: 72, yearPeak: 2010 },
  { name: 'Vega', origin: 'Español/Árabe', meaningDe: 'Die Fruchtbare Ebene', meaningEn: 'The Fertile Plain', meaningEs: 'La Llanura Fértil', gender: 'f', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 5, explanationDe: 'Astronomisch (Stern Vega) und spanisch. Im Aufstieg.', explanationEn: 'Astronomical (star Vega) and Spanish. On the rise.', explanationEs: 'Astronómico (estrella Vega) y español. En ascenso.', popularity: 65, yearPeak: 2023 },
  { name: 'Fernando', origin: 'Germánico', meaningDe: 'Der kühne Reisende', meaningEn: 'The Bold Traveler', meaningEs: 'El Viajero Audaz', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'ABBA-Song Assoziation. Königlich und traditionell.', explanationEn: 'ABBA song association. Royal and traditional.', explanationEs: 'Asociación con canción de ABBA. Real y tradicional.', popularity: 55, yearPeak: 2000 },
  { name: 'Jimena', origin: 'Hebreo', meaningDe: 'Die Erhörte', meaningEn: 'The Heard One', meaningEs: 'La Escuchada', gender: 'f', region: 'es', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 4, explanationDe: 'Sehr spanisch. El Cid\'s Frau. International schwer aussprechbar.', explanationEn: 'Very Spanish. El Cid\'s wife. Hard to pronounce internationally.', explanationEs: 'Muy español. Esposa del Cid. Difícil de pronunciar internacionalmente.', popularity: 60, yearPeak: 2019 },
  { name: 'Miguel', origin: 'Hebreo', meaningDe: 'Wer ist wie Gott?', meaningEn: 'Who is Like God?', meaningEs: '¿Quién como Dios?', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Cervantes und Engel Michael. Stark kulturell verankert.', explanationEn: 'Cervantes and Archangel Michael. Strongly culturally rooted.', explanationEs: 'Cervantes y Arcángel Miguel. Fuertemente arraigado culturalmente.', popularity: 72, yearPeak: 2005 },
  { name: 'Alma', origin: 'Latino/Hebreo', meaningDe: 'Die Seele', meaningEn: 'The Soul', meaningEs: 'El Alma', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Bedeutet "Seele" auf Spanisch. Sehr poetisch. Im starken Aufstieg.', explanationEn: 'Means "soul" in Spanish. Very poetic. Strongly rising.', explanationEs: 'Significa "alma". Muy poético. En fuerte ascenso.', popularity: 72, yearPeak: 2023 },
  { name: 'Iván', origin: 'Hebreo/Eslavo', meaningDe: 'Gott ist gnädig', meaningEn: 'God is Gracious', meaningEs: 'Dios es Misericordioso', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 2, explanationDe: 'Spanische Form von Ivan/Johann. Der Akzent macht international Schwierigkeiten.', explanationEn: 'Spanish form of Ivan/John. The accent causes international difficulties.', explanationEs: 'Forma española de Iván/Juan. El acento causa dificultades internacionales.', popularity: 55, yearPeak: 2005 },
  { name: 'Lola', origin: 'Español', meaningDe: 'Die Schmerzreiche', meaningEn: 'Lady of Sorrows', meaningEs: 'Señora de los Dolores', gender: 'f', region: 'es', bullyingScore: 4, intlScore: 1, careerScore: 3, trendScore: 4, explanationDe: 'Kurzform von Dolores. "Lola"-Song kann zu Spott führen. Frech und modern.', explanationEn: 'Short form of Dolores. "Lola" song can lead to teasing. Cheeky and modern.', explanationEs: 'Forma corta de Dolores. La canción "Lola" puede causar burlas. Atrevido y moderno.', popularity: 55, yearPeak: 2020 },
  { name: 'Gonzalo', origin: 'Germánico', meaningDe: 'Der Kampfbereite', meaningEn: 'Ready for Battle', meaningEs: 'Listo para la Batalla', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 4, careerScore: 2, trendScore: 3, explanationDe: 'Traditionell spanisch. International kaum bekannt.', explanationEn: 'Traditional Spanish. Hardly known internationally.', explanationEs: 'Tradicional español. Poco conocido internacionalmente.', popularity: 50, yearPeak: 2010 },
  { name: 'Inés', origin: 'Griego', meaningDe: 'Die Reine', meaningEn: 'The Pure One', meaningEs: 'La Pura', gender: 'f', region: 'es', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 3, explanationDe: 'Elegante spanische Agnes. Der Akzent ist international eine Hürde.', explanationEn: 'Elegant Spanish Agnes. The accent is an international hurdle.', explanationEs: 'Elegante forma española de Inés. El acento es una barrera internacional.', popularity: 58, yearPeak: 2018 },
  // === INTERNATIONAL/UNISEX NAMES ===
  { name: 'Robin', origin: 'Germanisch/Englisch', meaningDe: 'Der/Die Glänzende', meaningEn: 'The Bright/Famous One', meaningEs: 'El/La Brillante', gender: 'u', region: 'international', bullyingScore: 3, intlScore: 1, careerScore: 2, trendScore: 3, explanationDe: 'Unisex, international. Robin Hood Assoziation. Einfach und sympathisch.', explanationEn: 'Unisex, international. Robin Hood association. Simple and likeable.', explanationEs: 'Unisex, internacional. Asociación con Robin Hood. Simple y agradable.', popularity: 55, yearPeak: 2015 },
  { name: 'Alex', origin: 'Griechisch', meaningDe: 'Der/Die Beschützende', meaningEn: 'The Protector', meaningEs: 'El/La Protector/a', gender: 'u', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Universeller Kurzname. Funktioniert überall, geschlechtsneutral, modern.', explanationEn: 'Universal short name. Works everywhere, gender-neutral, modern.', explanationEs: 'Nombre corto universal. Funciona en todas partes, neutral en género, moderno.', popularity: 75, yearPeak: 2005 },
  { name: 'Kim', origin: 'Verschiedene', meaningDe: 'Königliche Festung', meaningEn: 'Royal Fortress', meaningEs: 'Fortaleza Real', gender: 'u', region: 'international', bullyingScore: 2, intlScore: 1, careerScore: 2, trendScore: 3, explanationDe: 'Kurz, universell, unisex. Kim Kardashian Assoziation dominant.', explanationEn: 'Short, universal, unisex. Kim Kardashian association dominant.', explanationEs: 'Corto, universal, unisex. Asociación con Kim Kardashian dominante.', popularity: 50, yearPeak: 2010 },
  { name: 'Sam', origin: 'Hebräisch', meaningDe: 'Von Gott erhört', meaningEn: 'Heard by God', meaningEs: 'Escuchado por Dios', gender: 'u', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 2, explanationDe: 'Universell, freundlich, geschlechtsneutral. Allein etwas kurz.', explanationEn: 'Universal, friendly, gender-neutral. A bit short on its own.', explanationEs: 'Universal, amigable, neutral en género. Un poco corto por sí solo.', popularity: 60, yearPeak: 2005 },
  { name: 'Luca', origin: 'Italienisch/Griechisch', meaningDe: 'Der/Die Leuchtende', meaningEn: 'The Light', meaningEs: 'La Luz', gender: 'u', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Unisex-Trendname. In Italien männlich, in Deutschland zunehmend unisex. Pixar-Film.', explanationEn: 'Unisex trend name. Male in Italy, increasingly unisex in Germany. Pixar movie.', explanationEs: 'Nombre de tendencia unisex. Masculino en Italia, cada vez más unisex. Película de Pixar.', popularity: 82, yearPeak: 2022 },
  { name: 'Andrea', origin: 'Griechisch', meaningDe: 'Der/Die Tapfere', meaningEn: 'The Brave One', meaningEs: 'El/La Valiente', gender: 'u', region: 'international', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'In DE/ES weiblich, in IT männlich. Geschlechterverwechslung möglich.', explanationEn: 'Female in DE/ES, male in Italy. Gender confusion possible.', explanationEs: 'Femenino en DE/ES, masculino en Italia. Posible confusión de género.', popularity: 60, yearPeak: 2005 },
  { name: 'Jordan', origin: 'Hebräisch', meaningDe: 'Der Herabfließende', meaningEn: 'The Descender', meaningEs: 'El que Desciende', gender: 'u', region: 'international', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'Michael Jordan Assoziation. Sportlich und dynamisch. Unisex.', explanationEn: 'Michael Jordan association. Sporty and dynamic. Unisex.', explanationEs: 'Asociación con Michael Jordan. Deportivo y dinámico. Unisex.', popularity: 62, yearPeak: 2005 },
  { name: 'Nico', origin: 'Griechisch', meaningDe: 'Der/Die Siegreiche', meaningEn: 'The Victorious One', meaningEs: 'El/La Victorioso/a', gender: 'u', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 4, explanationDe: 'Kurz, international, modern. In mehreren Kulturen gebräuchlich.', explanationEn: 'Short, international, modern. Used in multiple cultures.', explanationEs: 'Corto, internacional, moderno. Usado en múltiples culturas.', popularity: 68, yearPeak: 2018 },
  // A few more interesting/unusual names
  { name: 'Khaleesi', origin: 'Fiktiv (Game of Thrones)', meaningDe: 'Königin', meaningEn: 'Queen', meaningEs: 'Reina', gender: 'f', region: 'international', bullyingScore: 8, intlScore: 5, careerScore: 7, trendScore: 9, explanationDe: 'Fiktiver Name aus einer TV-Serie. Extrem riskant – die Figur endete als Villain.', explanationEn: 'Fictional name from a TV show. Extremely risky – the character ended as a villain.', explanationEs: 'Nombre ficticio de una serie de TV. Extremadamente arriesgado – el personaje terminó como villano.', popularity: 15, yearPeak: 2019 },
  { name: 'Apple', origin: 'Englisch', meaningDe: 'Der Apfel', meaningEn: 'The Apple Fruit', meaningEs: 'La Manzana', gender: 'f', region: 'en', bullyingScore: 9, intlScore: 2, careerScore: 8, trendScore: 9, explanationDe: 'Gwyneth Paltrows Tochter. Frucht als Name – maximales Hänselrisiko.', explanationEn: 'Gwyneth Paltrow\'s daughter. Fruit as a name – maximum teasing risk.', explanationEs: 'Hija de Gwyneth Paltrow. Fruta como nombre – máximo riesgo de burlas.', popularity: 5, yearPeak: 2004 },
  { name: 'Elon', origin: 'Hebräisch', meaningDe: 'Der Eichenbaum', meaningEn: 'The Oak Tree', meaningEs: 'El Roble', gender: 'm', region: 'international', bullyingScore: 6, intlScore: 2, careerScore: 4, trendScore: 7, explanationDe: 'Elon Musk Assoziation überwiegt alles. Sehr polarisierend.', explanationEn: 'Elon Musk association overwhelms everything. Very polarizing.', explanationEs: 'La asociación con Elon Musk lo domina todo. Muy polarizante.', popularity: 20, yearPeak: 2021 },
  { name: 'Nevaeh', origin: 'Englisch (Rückwärts)', meaningDe: 'Heaven rückwärts', meaningEn: 'Heaven spelled backwards', meaningEs: 'Heaven al revés', gender: 'f', region: 'en', bullyingScore: 7, intlScore: 6, careerScore: 6, trendScore: 7, explanationDe: 'Gimmick-Name – "Heaven" rückwärts. Wird oft falsch geschrieben und ausgesprochen.', explanationEn: 'Gimmick name – "Heaven" backwards. Often misspelled and mispronounced.', explanationEs: 'Nombre gimmick – "Heaven" al revés. A menudo mal escrito y pronunciado.', popularity: 35, yearPeak: 2010 },
  { name: 'Renesmee', origin: 'Fiktiv (Twilight)', meaningDe: 'Kombination aus Renée und Esmé', meaningEn: 'Combination of Renée and Esmé', meaningEs: 'Combinación de Renée y Esmé', gender: 'f', region: 'en', bullyingScore: 9, intlScore: 7, careerScore: 8, trendScore: 9, explanationDe: 'Erfundener Name aus Twilight. Maximaler Cringe-Faktor. Bitte nicht.', explanationEn: 'Made-up name from Twilight. Maximum cringe factor. Please don\'t.', explanationEs: 'Nombre inventado de Twilight. Máximo factor de vergüenza. Por favor no.', popularity: 5, yearPeak: 2012 },
  { name: 'Adolf', origin: 'Germanisch', meaningDe: 'Der edle Wolf', meaningEn: 'The Noble Wolf', meaningEs: 'El Lobo Noble', gender: 'm', region: 'de', bullyingScore: 10, intlScore: 2, careerScore: 10, trendScore: 10, explanationDe: 'Aus offensichtlichen historischen Gründen absolut nicht empfehlenswert.', explanationEn: 'For obvious historical reasons absolutely not recommended.', explanationEs: 'Por razones históricas obvias, absolutamente no recomendado.', popularity: 1, yearPeak: 1930 },
  { name: 'Isis', origin: 'Ägyptisch', meaningDe: 'Die Göttin', meaningEn: 'The Goddess', meaningEs: 'La Diosa', gender: 'f', region: 'international', bullyingScore: 10, intlScore: 2, careerScore: 9, trendScore: 10, explanationDe: 'Einst schöner Göttinnen-Name, aber durch die Terrororganisation ISIS völlig zerstört.', explanationEn: 'Once beautiful goddess name, but completely destroyed by the terrorist organization ISIS.', explanationEs: 'Una vez hermoso nombre de diosa, pero completamente destruido por la organización terrorista ISIS.', popularity: 2, yearPeak: 2005 },
  { name: 'Alexa', origin: 'Griechisch', meaningDe: 'Die Beschützerin', meaningEn: 'The Protector', meaningEs: 'La Protectora', gender: 'f', region: 'international', bullyingScore: 8, intlScore: 1, careerScore: 5, trendScore: 8, explanationDe: '"Alexa, mach das Licht an!" – Amazon hat diesen Namen effektiv ruiniert.', explanationEn: '"Alexa, turn on the lights!" – Amazon has effectively ruined this name.', explanationEs: '"¡Alexa, enciende la luz!" – Amazon ha arruinado efectivamente este nombre.', popularity: 20, yearPeak: 2015 },
  { name: 'Siri', origin: 'Nordisch', meaningDe: 'Die wunderschöne Siegerin', meaningEn: 'Beautiful Victory', meaningEs: 'Victoria Hermosa', gender: 'f', region: 'international', bullyingScore: 7, intlScore: 2, careerScore: 5, trendScore: 8, explanationDe: 'Apple Siri Assoziation. "Hey Siri" wird das Kind ein Leben lang hören.', explanationEn: 'Apple Siri association. "Hey Siri" the child will hear their whole life.', explanationEs: 'Asociación con Apple Siri. "Hey Siri" lo escuchará toda la vida.', popularity: 15, yearPeak: 2010 },
  { name: 'Thor', origin: 'Nordisch', meaningDe: 'Der Donner', meaningEn: 'The Thunder', meaningEs: 'El Trueno', gender: 'm', region: 'international', bullyingScore: 5, intlScore: 2, careerScore: 5, trendScore: 5, explanationDe: 'Marvel-Superheld und nordischer Gott. Schwer zu tragen als normaler Mensch.', explanationEn: 'Marvel superhero and Norse god. Hard to carry as a normal person.', explanationEs: 'Superhéroe de Marvel y dios nórdico. Difícil de llevar como persona normal.', popularity: 15, yearPeak: 2019 },
  // More German names for depth
  { name: 'Luise', origin: 'Germanisch', meaningDe: 'Die berühmte Kämpferin', meaningEn: 'Famous Warrior', meaningEs: 'Guerrera Famosa', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 3, explanationDe: 'Preußische Königin Luise. Traditionell, elegant, zunehmend beliebt.', explanationEn: 'Prussian Queen Luise. Traditional, elegant, increasingly popular.', explanationEs: 'Reina prusiana Luise. Tradicional, elegante, cada vez más popular.', popularity: 55, yearPeak: 2022 },
  { name: 'Emil', origin: 'Lateinisch', meaningDe: 'Der Eifrige', meaningEn: 'The Eager One', meaningEs: 'El Diligente', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Emil und die Detektive Assoziation. Retro-Trend, charmant.', explanationEn: 'Emil and the Detectives association. Retro trend, charming.', explanationEs: 'Asociación con Emil y los Detectives. Tendencia retro, encantador.', popularity: 60, yearPeak: 2022 },
  { name: 'Mats', origin: 'Schwedisch', meaningDe: 'Geschenk Gottes', meaningEn: 'Gift of God', meaningEs: 'Regalo de Dios', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 2, careerScore: 2, trendScore: 4, explanationDe: 'Mats Hummels boosted diesen Namen in DE. Nordisch-frisch.', explanationEn: 'Mats Hummels boosted this name in Germany. Nordic-fresh.', explanationEs: 'Mats Hummels impulsó este nombre en Alemania. Nórdico-fresco.', popularity: 55, yearPeak: 2018 },
  { name: 'Helena', origin: 'Griechisch', meaningDe: 'Die Leuchtende', meaningEn: 'The Radiant One', meaningEs: 'La Radiante', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Zeitlos elegant. Helena von Troja. International gut erkennbar.', explanationEn: 'Timelessly elegant. Helen of Troy. Internationally recognizable.', explanationEs: 'Atemporalmente elegante. Helena de Troya. Internacionalmente reconocible.', popularity: 62, yearPeak: 2015 },
  { name: 'Till', origin: 'Germanisch', meaningDe: 'Der Mächtige im Volk', meaningEn: 'Mighty Among People', meaningEs: 'Poderoso Entre el Pueblo', gender: 'm', region: 'de', bullyingScore: 3, intlScore: 4, careerScore: 3, trendScore: 3, explanationDe: 'Till Eulenspiegel Assoziation. Sehr deutsch. International schwierig.', explanationEn: 'Till Eulenspiegel association. Very German. Difficult internationally.', explanationEs: 'Asociación con Till Eulenspiegel. Muy alemán. Difícil internacionalmente.', popularity: 35, yearPeak: 2010 },
  { name: 'Annika', origin: 'Schwedisch', meaningDe: 'Die Anmutige', meaningEn: 'The Graceful One', meaningEs: 'La Agraciada', gender: 'f', region: 'de', bullyingScore: 1, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Pippi Langstrumpf Assoziation positiv. Nordisch-charmant.', explanationEn: 'Pippi Longstocking association positive. Nordic charming.', explanationEs: 'Asociación positiva con Pippi Calzaslargas. Encanto nórdico.', popularity: 45, yearPeak: 2005 },
  { name: 'Florian', origin: 'Lateinisch', meaningDe: 'Der Blühende', meaningEn: 'The Blooming One', meaningEs: 'El Floreciente', gender: 'm', region: 'de', bullyingScore: 2, intlScore: 3, careerScore: 1, trendScore: 2, explanationDe: 'Beliebter bayerischer Name. Solide, aber etwas datiert für Neugeborene.', explanationEn: 'Popular Bavarian name. Solid, but slightly dated for newborns.', explanationEs: 'Nombre bávaro popular. Sólido, pero algo anticuado para recién nacidos.', popularity: 45, yearPeak: 1995 },
  { name: 'Gisela', origin: 'Germanisch', meaningDe: 'Die Geisel/Das Pfand', meaningEn: 'The Pledge', meaningEs: 'La Prenda', gender: 'f', region: 'de', bullyingScore: 5, intlScore: 4, careerScore: 4, trendScore: 7, explanationDe: 'Stark veraltet. "Oma-Name" ohne Comeback-Potenzial.', explanationEn: 'Heavily dated. "Grandma name" without comeback potential.', explanationEs: 'Muy anticuado. "Nombre de abuela" sin potencial de regreso.', popularity: 5, yearPeak: 1960 },
  { name: 'Horst', origin: 'Germanisch', meaningDe: 'Der im Wald Lebende', meaningEn: 'Forest Dweller', meaningEs: 'El que Vive en el Bosque', gender: 'm', region: 'de', bullyingScore: 8, intlScore: 5, careerScore: 6, trendScore: 9, explanationDe: '"Ok Horst" als Meme. Klingt nach den 1950ern. Hohes Spottrisiko.', explanationEn: '"Ok Horst" as meme. Sounds like the 1950s. High mockery risk.', explanationEs: '"Ok Horst" como meme. Suena a los años 50. Alto riesgo de burla.', popularity: 3, yearPeak: 1955 },
  { name: 'Gertrude', origin: 'Germanisch', meaningDe: 'Die Speerkämpferin', meaningEn: 'The Spear Warrior', meaningEs: 'La Guerrera de Lanza', gender: 'f', region: 'de', bullyingScore: 7, intlScore: 4, careerScore: 5, trendScore: 8, explanationDe: 'Stark veraltet, kein Comeback in Sicht. Schwer zu tragen für ein Kind.', explanationEn: 'Heavily dated, no comeback in sight. Hard to carry for a child.', explanationEs: 'Muy anticuado, sin regreso a la vista. Difícil de llevar para un niño.', popularity: 2, yearPeak: 1940 },
  // More Spanish
  { name: 'Manuel', origin: 'Hebreo', meaningDe: 'Gott ist mit uns', meaningEn: 'God is With Us', meaningEs: 'Dios está con Nosotros', gender: 'm', region: 'es', bullyingScore: 2, intlScore: 2, careerScore: 1, trendScore: 2, explanationDe: 'Spanischer Klassiker. "Manolo" als Kurzform. Solide und warm.', explanationEn: 'Spanish classic. "Manolo" as short form. Solid and warm.', explanationEs: 'Clásico español. "Manolo" como diminutivo. Sólido y cálido.', popularity: 70, yearPeak: 2005 },
  { name: 'Claudia', origin: 'Latino', meaningDe: 'Die Hinkende', meaningEn: 'The Limping One', meaningEs: 'La Coja', gender: 'f', region: 'es', bullyingScore: 3, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Bedeutung problematisch, aber niemand kennt sie. Claudia Schiffer Assoziation.', explanationEn: 'Meaning problematic, but nobody knows it. Claudia Schiffer association.', explanationEs: 'Significado problemático, pero nadie lo conoce. Asociación con Claudia Schiffer.', popularity: 55, yearPeak: 2000 },
  { name: 'Lucas', origin: 'Griego', meaningDe: 'Der Lichtbringer', meaningEn: 'The Light Bearer', meaningEs: 'El Portador de Luz', gender: 'm', region: 'es', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 4, explanationDe: 'Internationale Form von Lukas. In Spanien und weltweit extrem beliebt.', explanationEn: 'International form of Lukas. Extremely popular in Spain and worldwide.', explanationEs: 'Forma internacional de Lucas. Extremadamente popular en España y mundialmente.', popularity: 90, yearPeak: 2022 },
  { name: 'Celia', origin: 'Latino', meaningDe: 'Die Himmlische', meaningEn: 'The Heavenly One', meaningEs: 'La Celestial', gender: 'f', region: 'es', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'Elegant und kurz. Celia Cruz Assoziation. Im Aufstieg in Spanien.', explanationEn: 'Elegant and short. Celia Cruz association. Rising in Spain.', explanationEs: 'Elegante y corto. Asociación con Celia Cruz. En ascenso en España.', popularity: 62, yearPeak: 2020 },
  // More English
  { name: 'Charlotte', origin: 'French', meaningDe: 'Die Freie', meaningEn: 'The Free Woman', meaningEs: 'La Mujer Libre', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 3, explanationDe: 'Prinzessin Charlotte. Elegant und königlich. International anerkannt.', explanationEn: 'Princess Charlotte. Elegant and royal. Internationally recognized.', explanationEs: 'Princesa Charlotte. Elegante y real. Reconocido internacionalmente.', popularity: 80, yearPeak: 2016 },
  { name: 'Mason', origin: 'English', meaningDe: 'Der Steinmetz', meaningEn: 'The Stone Worker', meaningEs: 'El Cantero', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 5, explanationDe: 'Amerikanischer Nachname als Vorname. Im Trend, aber Freimauerer-Assoziation.', explanationEn: 'American surname as first name. Trending, but Freemason association.', explanationEs: 'Apellido americano como nombre. En tendencia, pero asociación con masonería.', popularity: 75, yearPeak: 2012 },
  { name: 'Emily', origin: 'Latin', meaningDe: 'Die Eifrige', meaningEn: 'The Industrious One', meaningEs: 'La Trabajadora', gender: 'f', region: 'en', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Jahrelang #1 in USA/UK. Zeitlos elegant, aber sehr verbreitet.', explanationEn: 'Years at #1 in US/UK. Timelessly elegant, but very common.', explanationEs: 'Años en #1 en EE.UU./UK. Atemporalmente elegante, pero muy común.', popularity: 85, yearPeak: 2008 },
  { name: 'Logan', origin: 'Scottish', meaningDe: 'Der kleine Hohle', meaningEn: 'Little Hollow', meaningEs: 'Pequeño Hueco', gender: 'm', region: 'en', bullyingScore: 2, intlScore: 3, careerScore: 2, trendScore: 5, explanationDe: 'X-Men Wolverine. Logan Paul Assoziation problematisch.', explanationEn: 'X-Men Wolverine. Logan Paul association problematic.', explanationEs: 'X-Men Wolverine. Asociación con Logan Paul problemática.', popularity: 72, yearPeak: 2017 },
  { name: 'Zoe', origin: 'Griechisch', meaningDe: 'Das Leben', meaningEn: 'Life', meaningEs: 'La Vida', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 2, careerScore: 1, trendScore: 4, explanationDe: 'Kurz, bedeutungsvoll, modern. Umlaut-Probleme (Zoë vs. Zoe).', explanationEn: 'Short, meaningful, modern. Umlaut issues (Zoë vs. Zoe).', explanationEs: 'Corto, significativo, moderno. Problemas de diéresis (Zoë vs. Zoe).', popularity: 72, yearPeak: 2018 },
  { name: 'David', origin: 'Hebräisch', meaningDe: 'Der Geliebte', meaningEn: 'The Beloved', meaningEs: 'El Amado', gender: 'm', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 1, explanationDe: 'Einer der internationalsten Namen. Funktioniert in jeder Sprache und Kultur.', explanationEn: 'One of the most international names. Works in every language and culture.', explanationEs: 'Uno de los nombres más internacionales. Funciona en todos los idiomas y culturas.', popularity: 80, yearPeak: 1990 },
  { name: 'Anna', origin: 'Hebräisch', meaningDe: 'Die Anmutige', meaningEn: 'The Graceful One', meaningEs: 'La Agraciada', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Palindrom, zeitlos, global. Vielleicht der sicherste Name der Welt.', explanationEn: 'Palindrome, timeless, global. Perhaps the safest name in the world.', explanationEs: 'Palíndromo, atemporal, global. Quizás el nombre más seguro del mundo.', popularity: 82, yearPeak: 2000 },
  { name: 'Michael', origin: 'Hebräisch', meaningDe: 'Wer ist wie Gott?', meaningEn: 'Who is Like God?', meaningEs: '¿Quién como Dios?', gender: 'm', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Der beliebteste Name des 20. Jahrhunderts. Absolut zeitlos.', explanationEn: 'The most popular name of the 20th century. Absolutely timeless.', explanationEs: 'El nombre más popular del siglo XX. Absolutamente atemporal.', popularity: 78, yearPeak: 1985 },
  { name: 'Sarah', origin: 'Hebräisch', meaningDe: 'Die Fürstin', meaningEn: 'The Princess', meaningEs: 'La Princesa', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Biblisch, elegant, zeitlos. Funktioniert in allen westlichen Kulturen.', explanationEn: 'Biblical, elegant, timeless. Works in all Western cultures.', explanationEs: 'Bíblico, elegante, atemporal. Funciona en todas las culturas occidentales.', popularity: 80, yearPeak: 2000 },
  { name: 'Julia', origin: 'Lateinisch', meaningDe: 'Die dem Jupiter Geweihte', meaningEn: 'Devoted to Jupiter', meaningEs: 'Devota a Júpiter', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Römisch, elegant, zeitlos. Julia Roberts Assoziation positiv.', explanationEn: 'Roman, elegant, timeless. Julia Roberts association positive.', explanationEs: 'Romano, elegante, atemporal. Asociación con Julia Roberts positiva.', popularity: 75, yearPeak: 2000 },
  { name: 'Simon', origin: 'Hebräisch', meaningDe: 'Der Erhörte', meaningEn: 'The Heard One', meaningEs: 'El Escuchado', gender: 'm', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Biblisch und international. Einfach, seriös, zeitlos.', explanationEn: 'Biblical and international. Simple, serious, timeless.', explanationEs: 'Bíblico e internacional. Simple, serio, atemporal.', popularity: 55, yearPeak: 2005 },
  { name: 'Laura', origin: 'Lateinisch', meaningDe: 'Die Lorbeergekrönte', meaningEn: 'The Laurel-Crowned', meaningEs: 'La Coronada de Laurel', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Römisch, universell, elegant. Einer der sichersten internationalen Namen.', explanationEn: 'Roman, universal, elegant. One of the safest international names.', explanationEs: 'Romano, universal, elegante. Uno de los nombres internacionales más seguros.', popularity: 75, yearPeak: 2005 },
  { name: 'Nikita', origin: 'Griechisch/Russisch', meaningDe: 'Der/Die Unbesiegte', meaningEn: 'The Unconquered', meaningEs: 'El/La Invicto/a', gender: 'u', region: 'international', bullyingScore: 3, intlScore: 2, careerScore: 2, trendScore: 3, explanationDe: 'In Russland männlich, in DE eher weiblich. Geschlechterverwirrung möglich.', explanationEn: 'Male in Russia, rather female in Germany. Gender confusion possible.', explanationEs: 'Masculino en Rusia, más femenino en Alemania. Posible confusión de género.', popularity: 35, yearPeak: 2005 },
  { name: 'Max', origin: 'Lateinisch', meaningDe: 'Der Größte', meaningEn: 'The Greatest', meaningEs: 'El Más Grande', gender: 'm', region: 'international', bullyingScore: 2, intlScore: 1, careerScore: 2, trendScore: 3, explanationDe: 'Kurz, kraftvoll, universal. Auch Hundename – das nervt manche.', explanationEn: 'Short, powerful, universal. Also a dog name – that annoys some.', explanationEs: 'Corto, poderoso, universal. También nombre de perro – eso molesta a algunos.', popularity: 72, yearPeak: 2010 },
  { name: 'Lisa', origin: 'Hebräisch', meaningDe: 'Die Gott Geweihte', meaningEn: 'Devoted to God', meaningEs: 'Devota a Dios', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 3, explanationDe: 'Kurzform von Elisabeth. Einfach, freundlich, zeitlos. Etwas häufig.', explanationEn: 'Short form of Elisabeth. Simple, friendly, timeless. Somewhat common.', explanationEs: 'Forma corta de Elisabeth. Simple, amigable, atemporal. Algo común.', popularity: 70, yearPeak: 2000 },
  { name: 'Leo', origin: 'Lateinisch', meaningDe: 'Der Löwe', meaningEn: 'The Lion', meaningEs: 'El León', gender: 'm', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 2, trendScore: 5, explanationDe: 'Trendy, kurz, stark. Leonardo DiCaprio Assoziation. Weltweit beliebt.', explanationEn: 'Trendy, short, strong. Leonardo DiCaprio association. Globally popular.', explanationEs: 'De moda, corto, fuerte. Asociación con Leonardo DiCaprio. Globalmente popular.', popularity: 88, yearPeak: 2023 },
  { name: 'Eva', origin: 'Hebräisch', meaningDe: 'Die Lebensspendende', meaningEn: 'The Life-Giver', meaningEs: 'La Dadora de Vida', gender: 'f', region: 'international', bullyingScore: 1, intlScore: 1, careerScore: 1, trendScore: 2, explanationDe: 'Biblisch, universell, kurz. Eva Longoria. Absolut sicher.', explanationEn: 'Biblical, universal, short. Eva Longoria. Absolutely safe.', explanationEs: 'Bíblico, universal, corto. Eva Longoria. Absolutamente seguro.', popularity: 65, yearPeak: 2005 },
  { name: 'Jayden', origin: 'Modern Englisch', meaningDe: 'Moderne Erfindung', meaningEn: 'Modern Invention', meaningEs: 'Invención Moderna', gender: 'm', region: 'en', bullyingScore: 4, intlScore: 4, careerScore: 4, trendScore: 7, explanationDe: 'Teil der -ayden Welle (Jayden, Kayden, Brayden). Kurzlebiger Trend.', explanationEn: 'Part of the -ayden wave (Jayden, Kayden, Brayden). Short-lived trend.', explanationEs: 'Parte de la ola -ayden (Jayden, Kayden, Brayden). Tendencia pasajera.', popularity: 55, yearPeak: 2012 },
  { name: 'Madison', origin: 'Englisch', meaningDe: 'Sohn des Maud', meaningEn: 'Son of Maud', meaningEs: 'Hijo de Maud', gender: 'f', region: 'en', bullyingScore: 3, intlScore: 4, careerScore: 2, trendScore: 5, explanationDe: 'War männlich, wurde durch "Splash" (1984) weiblich. Trend-Welle bereits vorbei.', explanationEn: 'Was male, became female through "Splash" (1984). Trend wave already passed.', explanationEs: 'Era masculino, se volvió femenino por "Splash" (1984). La ola de tendencia ya pasó.', popularity: 50, yearPeak: 2005 },
];

async function main() {
  console.log(`Seeding ${names.length} names...`)
  
  for (const n of names) {
    const overall = calcRegret(n.bullyingScore, n.intlScore, n.careerScore, n.trendScore)
    await prisma.name.upsert({
      where: { name: n.name },
      update: {
        origin: n.origin,
        meaningDe: n.meaningDe,
        meaningEn: n.meaningEn,
        meaningEs: n.meaningEs,
        gender: n.gender,
        region: n.region,
        bullyingScore: n.bullyingScore,
        intlScore: n.intlScore,
        careerScore: n.careerScore,
        trendScore: n.trendScore,
        overallRegret: overall,
        explanationDe: n.explanationDe,
        explanationEn: n.explanationEn,
        explanationEs: n.explanationEs,
        popularity: n.popularity,
        yearPeak: n.yearPeak,
      },
      create: {
        name: n.name,
        origin: n.origin,
        meaningDe: n.meaningDe,
        meaningEn: n.meaningEn,
        meaningEs: n.meaningEs,
        gender: n.gender,
        region: n.region,
        bullyingScore: n.bullyingScore,
        intlScore: n.intlScore,
        careerScore: n.careerScore,
        trendScore: n.trendScore,
        overallRegret: overall,
        explanationDe: n.explanationDe,
        explanationEn: n.explanationEn,
        explanationEs: n.explanationEs,
        popularity: n.popularity,
        yearPeak: n.yearPeak,
      },
    })
  }
  
  console.log(`Done! Seeded ${names.length} names.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
